name: CFBanner
version: 1.7
author: CainFoool
main: me.cain.cfbanner.CFBanner
softdepend: [Spout]
commands:
   cfbanner:
      description: Check The CFBanner settings
      usage: 
permissions:
    cf.*:
        description: Gives access to all CFBanner commands
        children:
            cf.allowfly: true
            cf.allowcheat: true
            cf.command: true
    cf.allowfly:
        description: Grants access to flying
        default: op
    cf.allowcheat:
        description: Grants access to cheating
        default: op
    cf.command:
        description: Allows you to use cfbanner command
        default: op